/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTopicTopicIdRouteRouteImport } from './routes/_protected.topic.$topicId/route'
import { Route as ProtectedChatThreadIdRouteRouteImport } from './routes/_protected.chat.$threadId/route'
import { Route as ProtectedChatThreadIdIndexRouteImport } from './routes/_protected.chat.$threadId/index'
import { Route as ProtectedTopicTopicIdFilesRouteImport } from './routes/_protected.topic.$topicId/files'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTopicTopicIdRouteRoute =
  ProtectedTopicTopicIdRouteRouteImport.update({
    id: '/topic/$topicId',
    path: '/topic/$topicId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedChatThreadIdRouteRoute =
  ProtectedChatThreadIdRouteRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedChatThreadIdIndexRoute =
  ProtectedChatThreadIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedChatThreadIdRouteRoute,
  } as any)
const ProtectedTopicTopicIdFilesRoute =
  ProtectedTopicTopicIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ProtectedTopicTopicIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offline': typeof OfflineRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ProtectedChatThreadIdRouteRouteWithChildren
  '/topic/$topicId': typeof ProtectedTopicTopicIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/topic/$topicId/files': typeof ProtectedTopicTopicIdFilesRoute
  '/chat/$threadId/': typeof ProtectedChatThreadIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offline': typeof OfflineRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/topic/$topicId': typeof ProtectedTopicTopicIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/topic/$topicId/files': typeof ProtectedTopicTopicIdFilesRoute
  '/chat/$threadId': typeof ProtectedChatThreadIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/offline': typeof OfflineRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_protected/chat/$threadId': typeof ProtectedChatThreadIdRouteRouteWithChildren
  '/_protected/topic/$topicId': typeof ProtectedTopicTopicIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/topic/$topicId/files': typeof ProtectedTopicTopicIdFilesRoute
  '/_protected/chat/$threadId/': typeof ProtectedChatThreadIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offline'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/topic/$topicId'
    | '/api/auth/$'
    | '/topic/$topicId/files'
    | '/chat/$threadId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/offline'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/api/chat'
    | '/topic/$topicId'
    | '/api/auth/$'
    | '/topic/$topicId/files'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/offline'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/settings'
    | '/api/chat'
    | '/_protected/chat/$threadId'
    | '/_protected/topic/$topicId'
    | '/api/auth/$'
    | '/_protected/topic/$topicId/files'
    | '/_protected/chat/$threadId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/topic/$topicId': {
      id: '/_protected/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof ProtectedTopicTopicIdRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/$threadId': {
      id: '/_protected/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ProtectedChatThreadIdRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/$threadId/': {
      id: '/_protected/chat/$threadId/'
      path: '/'
      fullPath: '/chat/$threadId/'
      preLoaderRoute: typeof ProtectedChatThreadIdIndexRouteImport
      parentRoute: typeof ProtectedChatThreadIdRouteRoute
    }
    '/_protected/topic/$topicId/files': {
      id: '/_protected/topic/$topicId/files'
      path: '/files'
      fullPath: '/topic/$topicId/files'
      preLoaderRoute: typeof ProtectedTopicTopicIdFilesRouteImport
      parentRoute: typeof ProtectedTopicTopicIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedChatThreadIdRouteRouteChildren {
  ProtectedChatThreadIdIndexRoute: typeof ProtectedChatThreadIdIndexRoute
}

const ProtectedChatThreadIdRouteRouteChildren: ProtectedChatThreadIdRouteRouteChildren =
  {
    ProtectedChatThreadIdIndexRoute: ProtectedChatThreadIdIndexRoute,
  }

const ProtectedChatThreadIdRouteRouteWithChildren =
  ProtectedChatThreadIdRouteRoute._addFileChildren(
    ProtectedChatThreadIdRouteRouteChildren,
  )

interface ProtectedTopicTopicIdRouteRouteChildren {
  ProtectedTopicTopicIdFilesRoute: typeof ProtectedTopicTopicIdFilesRoute
}

const ProtectedTopicTopicIdRouteRouteChildren: ProtectedTopicTopicIdRouteRouteChildren =
  {
    ProtectedTopicTopicIdFilesRoute: ProtectedTopicTopicIdFilesRoute,
  }

const ProtectedTopicTopicIdRouteRouteWithChildren =
  ProtectedTopicTopicIdRouteRoute._addFileChildren(
    ProtectedTopicTopicIdRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedChatThreadIdRouteRoute: typeof ProtectedChatThreadIdRouteRouteWithChildren
  ProtectedTopicTopicIdRouteRoute: typeof ProtectedTopicTopicIdRouteRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedChatThreadIdRouteRoute: ProtectedChatThreadIdRouteRouteWithChildren,
  ProtectedTopicTopicIdRouteRoute: ProtectedTopicTopicIdRouteRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  OfflineRoute: OfflineRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
